filename = sprintf("%s/parameters.txt", dir_name,no)
sink(file = filename, append=TRUE)
sprintf("N_bact: %s", n_bact)
sprintf("Steps: %s", steps)
sprintf("dt: %s", dt)
sprintf("Runtime: %s", total_runtime)
sprintf("M: %s", M)
sprintf("CheZ: %s", Z_tot)
sprintf("CheY: %s", Y_tot)
sprintf("grad_x0: %s", grad_x0)
sprintf("grad_x1: %s", grad_x1)
sprintf("grad_x2: %s", grad_x2)
sprintf("grad_x3: %s", grad_x3)
sprintf("Box_x: %s", box_dim[1])
sprintf("Box_y: %s", box_dim[2])
sink(file=NULL)
