all:
	g++ -std=c++11 snm_wrapper.cpp snm_simulation.cpp snm_functions.cpp snm_variables.cpp snm_parameters.cpp snm_functions.h snm_variables.h && ./a
target:
	g++ -std=c++11 snm_wrapper.cpp snm_simulation.cpp snm_functions.cpp snm_variables.cpp snm_parameters.cpp snm_functions.h snm_variables.h -o $(out)